@baseUrl = http://localhost:8989
@id=1755677180

### GET m-biodata/{id}
GET {{baseUrl}}/api/v1/m-biodata/{{id}}
Content-Type: application/json

### GET m-biodata/list
GET {{baseUrl}}/api/v1/m-biodata/list
Content-Type: application/json

### GET m-biodata/pagination
GET {{baseUrl}}/api/v1/m-biodata/pagination?page=1&size=2
Content-Type: application/json

### POST m-biodata/pagination
POST {{baseUrl}}/api/v1/m-biodata/pagination?page=1&size=2
Content-Type: application/json

{
    "sorts": [{"id": "fullname", "desc": true}],
    "filters": []
}

### POST m-biodata
POST {{baseUrl}}/api/v1/m-biodata
Content-Type: application/json

{
    "fullname": "okey dokey",
    "mobile_phone": "087263547382"
}

### PUT m-biodata/{id}
PUT {{baseUrl}}/api/v1/m-biodata/{{id}}
Content-Type: application/json

{
    "fullname": "okey dokey 1212",
    "mobile_phone": "0872635473",
    "image_path": null,
    "image": null
}

### DELETE m-biodata/{id}
DELETE {{baseUrl}}/api/v1/m-biodata/{{id}}
Content-Type: application/json


### POST m-biodata/image
POST {{baseUrl}}/api/v1/m-biodata/image/{{id}}
Content-Type: multipart/form-data; boundary=----boundary123

------boundary123
Content-Disposition: form-data; name="image"; filename="file_example_JPG_100kB.jpg"
Content-Type: image/jpeg

< ./data/sample/file_example_JPG_100kB.jpg
------boundary123--