GET {{base_url}}/api/v1/m-biodata/{{id_mbiodata}}
Content-Type: application/json
###
GET {{base_url}}/api/v1/m-biodata/list
Content-Type: application/json

> {% client.global.set("id_mbiodata", response.body.data[0].id); %}
###
GET {{base_url}}/api/v1/m-biodata/pagination?page=0&size=2
Content-Type: application/json
###
POST {{base_url}}/api/v1/m-biodata/pagination?page=1&size=2
Content-Type: application/json

{
    "sorts": [{"id_mbiodata": "fullname", "desc": true}],
    "filters": []
}
###
POST {{base_url}}/api/v1/m-biodata
Content-Type: application/json

{
    "fullname": "okey dokey",
    "mobile_phone": "087263547382"
}
###
PUT {{base_url}}/api/v1/m-biodata/{{id_mbiodata}}
Content-Type: application/json

{
    "fullname": "okey dokey 1212",
    "mobile_phone": "0872635473",
    "image_path": null,
    "image": null
}
###
DELETE {{base_url}}/api/v1/m-biodata/{{id_mbiodata}}
Content-Type: application/json
###
POST {{base_url}}/api/v1/m-biodata/image/{{id_mbiodata}}
Content-Type: multipart/form-data; boundary=----boundary123

------boundary123
Content-Disposition: form-data; name="image"; filename="file_example_JPG_100kB.jpg"
Content-Type: image/jpeg

< ./data/sample/file_example_JPG_100kB.jpg
------boundary123--